
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html <?php language_attributes(); ?>>

<head>
<meta charset="<?php bloginfo('charset'); ?>" />
<title><?php wp_title('&ndash; ', true, 'right'); bloginfo('name'); ?></title>
<link href="<?php bloginfo('template_url'); ?>/css/cgt-layout.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="container">
    <div id="background">

    <div id="page">

        <!--
            Np longer need <?php bloginfo('template_url'); ?>/images/cgt-logo.png
            as it has been merged into header due to PNG issues
        -->

        <div class="mainmenu">
        <!-- begin: mainmenu (autogenerated) -->
        <?php wp_nav_menu(array(
                'theme_location' => 'mainmenu',
                'container' => false,
        )); ?>
        <!-- end: mainmenu (autogenerated) -->
        </div><!-- end: mainmenu -->

