
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html <?php language_attributes(); ?>>

<head>
<meta charset="<?php bloginfo('charset'); ?>" />
<title><?php wp_title('&ndash; ', true, 'right'); bloginfo('name'); ?></title>
<link href="<?php bloginfo('template_url'); ?>/css/cgt-layout.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="container">
    <div id="background">

    <div id="page">

        <div id="logo"><img src="<?php bloginfo('template_url'); ?>/images/cgt-logo.png" alt="Fleet Street Talks" width="256" height="173" /></div>

        <!-- begin: mainmenu (autogenerated) -->
        <?php wp_nav_menu(array(
                'container-class' => 'menu-header',
                'menu_class' => 'mainmenu',
                'theme-location' => 'primary'
        )); ?>
        <!-- end: mainmenu (autogenerated) -->

