<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo('charset'); ?>" />
<title><?php wp_title('&ndash; ', true, 'right'); bloginfo('name'); ?></title>
<link href="<?php bloginfo('template_url'); ?>/css/cgt-layout.css" rel="stylesheet" type="text/css" />
</head>

<body>
<div id="container">
	<div id="background">

 	<div id="page">

        <div id="logo"><img src="<?php bloginfo('template_url'); ?>/images/cgt-logo.png" alt="Fleet Street Talks" width="256" height="173" /></div>

        <!-- begin: mainmenu (autogenerated) -->
        <?php wp_nav_menu(array(
                'container-class' => 'menu-header',
                'menu_class' => 'mainmenu',
                'theme-location' => 'primary'
        )); ?>
        <!-- end: mainmenu (autogenerated) -->

		<div id="content">
		  <img src="images/welcome-title.png" alt="Welcome" width="164" height="45" />
		  <p>Welcome to Covent Garden Talks!</p>
		  <p>We are a network of Christians who work around the Covent Garden area. Our big aim is to help people working  in this part of London come face to face with the message of Jesus Christ.</p>
	      <p>We welcome people at any stage of Christian understanding,  whether you would call yourself a Christian or are just interested in finding  out more about the Christian faith.</p>
	      <p>&nbsp;</p>
	      <p>What's on?</p>
        <p><a href="lunchtime.html">Lunchtime Talk<br />
	      </a><a href="christianityexplored.html">Christianity Explored</a><br />
	      <a href="regulars.html">Prayer meeting</a></p>
        <p>&nbsp;</p>
		</div><!-- end: content -->

		<div id="rightcolumn">
		  <h1><img src="images/OctaveC.jpg" width="210" height="147" /></h1>
		  <h1>&nbsp;</h1>
        </div><!-- end: rightcolumn -->

 	</div><!-- end: page -->

	<div id="footer">
        <p>copyright &copy; <a href="http://www.coventgardentalks.org">covent garden talks</a>
            : design by <a href="http://www.bendesmond.com" target="_blank">bendesmond.com</a>
            : <a href="<?php echo admin_url() ?>" target="_blank">managed</a> by <a href="http://www.wordpress.org">wordpress</a></p>
    </div><!-- end: footer -->

    </div><!-- end: background -->
</div><!-- end: container -->
</body>
</html>

